### ISSUE TITLE
Create showcast screenshot for wowinterface

### ISSUE THREAD

**Issue by spiralofhope** [TekNoLogic/Blipstick#1]
http://www.wowinterface.com/downloads/info8838-Blipstick.html#info

Create a simple before and after screenshot.

On the left is a screenshot of the original minimap with the original blips.

On the right of that same screenshot is the original minimap with one of the blip skins.  e.g. the smaller blips.

**Comment by tekkub** [comment]
Sorry I don't do screenshots.

**Comment by spiralofhope** [comment]
If you'd like I'll make them once blipstick is working for me.
